CREATE TABLE `taxloan_report_daily` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增主键',
`report_day` date DEFAULT NULL COMMENT '统计日期',
`mcht_cnt_total` int(20) DEFAULT NULL COMMENT '累计装插件企业数',
`mcht_cnt_incre` int(20) DEFAULT NULL COMMENT '企业数增加',
`saleinvoice_cnt_total` bigint(30) DEFAULT NULL COMMENT '累计采集发票数',
`saleinvoice_cnt_incre` bigint(30) DEFAULT NULL COMMENT '发票数增加',
`apply_cnt_total` int(20) DEFAULT NULL COMMENT '累计银行申请户数',
`apply_cnt_incre` int(20) DEFAULT NULL COMMENT '银行申请户数当日新增',
`bank_approved_cnt_total` int(20) DEFAULT NULL COMMENT '累计银行通过户数',
`bank_approved_cnt_incre` int(20) DEFAULT NULL COMMENT '银行通过户数当日新增',
`bank_amt_total` decimal(20,2) DEFAULT NULL COMMENT '累计银行授信金额',
`bank_amt_incre` decimal(20,2) DEFAULT NULL COMMENT '当日银行新增授信金额',
`preloan_approved_cnt_total` int(20) DEFAULT NULL COMMENT '累计贷前通过户数',
`preloan_approved_cnt_incre` int(20) DEFAULT NULL COMMENT '贷前通过户数当日新增',
`use_cnt_total` int(20) DEFAULT NULL COMMENT '累计放款户数',
`use_cnt_incre` int(20) DEFAULT NULL COMMENT '放款户数当日新增',
`use_amt_total` decimal(20,2) DEFAULT NULL COMMENT '累计放款金额',
`use_amt_incre` decimal(20,2) DEFAULT NULL COMMENT '当日新增放款金额',
`bank_approved_rate` decimal(5,2) DEFAULT NULL COMMENT '累计银行通过率',
`preloan_approved_rate` decimal(5,2) DEFAULT NULL COMMENT '累计贷前通过率',
`use_rate` decimal(5,2) DEFAULT NULL COMMENT '累计放款率',
`is_delete` char(1) DEFAULT NULL COMMENT '逻辑删除，1.是，0.否',
`create_time` date DEFAULT NULL COMMENT '创建时间',
`create_user` varchar(100) DEFAULT NULL COMMENT '创建人',
`modify_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
`modify_user` varchar(100) DEFAULT NULL COMMENT '修改人',
PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=39 DEFAULT CHARSET=utf8 COMMENT='【税金贷】日统计报表';

