
--------------------------------------------------------------------
----------------------MYSQL建表语句------------------------

--原始测试数据表，发票表
DROP TABLE IF EXISTS saleinvoice;
CREATE TABLE `saleinvoice` (
cid varchar(50) NOT NULL COMMENT  '主键',
invoiceid varchar(50) DEFAULT NULL COMMENT  '发票GUID',
jztype varchar(50) DEFAULT NULL COMMENT  '介质类型',
invoicetype varchar(50) DEFAULT NULL COMMENT  '发票种类',
invoicecode varchar(50) DEFAULT NULL COMMENT  '类别代码',
invoiceno varchar(50) DEFAULT NULL COMMENT  '发票号码',
buyername varchar(50) DEFAULT NULL COMMENT  '购方名称',
buyertaxno varchar(50) DEFAULT NULL COMMENT  '购方税号',
buyeraddtel varchar(50) DEFAULT NULL COMMENT  '购方地址电话',
buyerbankno varchar(50) DEFAULT NULL COMMENT  '购方银行帐号',
sellername varchar(50) DEFAULT NULL COMMENT  '销方名称',
sellertaxno varchar(50) DEFAULT NULL COMMENT  '销方税号',
selleraddtel varchar(50) DEFAULT NULL COMMENT  '销方地址电话',
sellerbankno varchar(50) DEFAULT NULL COMMENT  '销方银行帐号',
ciphertext varchar(50) DEFAULT NULL COMMENT  '密文',
totalamount float DEFAULT NULL COMMENT  '合计金额',
taxrate float DEFAULT NULL COMMENT  '税率',
totaltax float DEFAULT NULL COMMENT  '合计税额',
invoicedate DATE DEFAULT NULL COMMENT  '开票日期',
comments varchar(50) DEFAULT NULL COMMENT  '备注',
makeinvoiceperson varchar(50) DEFAULT NULL COMMENT  '开票人',
recheckperson varchar(50) DEFAULT NULL COMMENT  '复核人',
gatheringperson varchar(50) DEFAULT NULL COMMENT  '收款人',
detaillistflag bit DEFAULT NULL COMMENT  '清单标志',
cancelflag bit DEFAULT NULL COMMENT  '作废标志',
repairflag bit DEFAULT NULL COMMENT  '修复标志',
printflag bit DEFAULT NULL COMMENT  '打印标志',
autono int DEFAULT 0 COMMENT  '自动序号',
createtime datetime DEFAULT NULL COMMENT  '创建时间',
incomingstate int DEFAULT 0 COMMENT  '传入认证系统状态',
incomingusername varchar(50) DEFAULT NULL COMMENT  '传入认证系统用户名',
incomingtime DATE DEFAULT NULL COMMENT  '传入认证系统时间',
authstate int DEFAULT 0 COMMENT  '认证状态',
matchstate int DEFAULT 0 COMMENT  '匹配状态',
authusername varchar(50) DEFAULT NULL COMMENT  '认证用户名',
authtime datetime DEFAULT NULL COMMENT  '认证时间',
makeinvoicedeviceno int DEFAULT 0 COMMENT  '开票机号',
checkcode varchar(50) DEFAULT NULL COMMENT  '校验码',
encryptionver varchar(50) DEFAULT NULL COMMENT  '加密版本号',
buyerno varchar(50) DEFAULT NULL COMMENT  '购方编号',
salebillno varchar(50) DEFAULT NULL COMMENT  '销售单据编号',
machineno varchar(50) DEFAULT NULL COMMENT  '机器编号',
carriertaxno varchar(50) DEFAULT NULL COMMENT  '承运人税号',
taxofficecode varchar(50) DEFAULT NULL COMMENT  '主管税务机关代码',
insteadorgcode varchar(50) DEFAULT NULL COMMENT  '代开单位代码',
lastauthdate DATE DEFAULT NULL COMMENT  '最迟抵扣日期',
invoicecontent varchar(50) DEFAULT NULL COMMENT  '发票内容',
deliverstate int DEFAULT 0 COMMENT  '投递状态',
expresscompany varchar(50) DEFAULT NULL COMMENT  '快递公司',
expressno varchar(50) DEFAULT NULL COMMENT  '快递单号',
sender varchar(50) DEFAULT NULL COMMENT  '寄件人',
sendertel varchar(50) DEFAULT NULL COMMENT  '寄件人电话',
senderadd varchar(50) DEFAULT NULL COMMENT  '寄件人地址',
receiver varchar(50) DEFAULT NULL COMMENT  '收件人',
receivertel varchar(50) DEFAULT NULL COMMENT  '收件人电话',
receiveradd varchar(50) DEFAULT NULL COMMENT  '收件人地址',
receiveconfirm varchar(50) DEFAULT NULL COMMENT  '确认收件',
approvestate varchar(50) DEFAULT NULL COMMENT  '审核状态',
approvers varchar(50) DEFAULT NULL COMMENT  '审核人',
lastapprover varchar(50) DEFAULT NULL COMMENT  '最后审核人',
lastapprovedate DATE DEFAULT NULL COMMENT  '最后审核日期',
approvecomment varchar(50) DEFAULT NULL COMMENT  '最后审批意见',
nextapprover varchar(50) DEFAULT NULL COMMENT  '下一个审核人',
processinstanceid varchar(50) DEFAULT NULL COMMENT  '流程ID',
noticestate int DEFAULT 0 COMMENT  '提醒状态',
inputperson varchar(50) DEFAULT NULL COMMENT  '录入人',
senttobank int DEFAULT 0 COMMENT  '发送到银行状态',
senterrtimes int DEFAULT 0 COMMENT  '发送错误次数',
logno varchar(50) DEFAULT NULL COMMENT  '流水号',
responecode varchar(50) DEFAULT NULL COMMENT  '返回码',
responeexplain varchar(50) DEFAULT NULL COMMENT  '返回码说明',
senttime varchar(50) DEFAULT NULL COMMENT  '发送时间',
sentoperator varchar(50) DEFAULT NULL COMMENT  '发送操作人',
invoicebranch varchar(50) DEFAULT NULL COMMENT  '开票网点',
srctype int DEFAULT 0 COMMENT  '来源类型',
writebackstate int DEFAULT 0 COMMENT  '回写状态',
writebacktime datetime DEFAULT NULL COMMENT  '回写时间',
querycode varchar(50) DEFAULT NULL COMMENT  '查询码',
taxcode varchar(50) DEFAULT NULL COMMENT  '税控码',
password varchar(50) DEFAULT NULL COMMENT  '密码',
checkstate int DEFAULT 0 COMMENT  '查验状态',
checkresult varchar(50) DEFAULT NULL COMMENT  '查验结果备注',
invoicearea varchar(50) DEFAULT NULL COMMENT  '发票区域',
cityid varchar(50) DEFAULT NULL COMMENT  '发票城市ID',
checkurl varchar(50) DEFAULT NULL COMMENT  '查验网址',
agentcode varchar(50) DEFAULT NULL COMMENT  '代理代码',
billid varchar(50) DEFAULT NULL COMMENT  '关联单据ID',
billno varchar(50) DEFAULT NULL COMMENT  '关联单据号码',
source varchar(50) DEFAULT NULL COMMENT  '数据来源',
forwordstate int DEFAULT 0 COMMENT  '转发状态',
ordercid varchar(50) DEFAULT NULL COMMENT  '订单ID',
ordercode varchar(50) DEFAULT NULL COMMENT  '订单代码',
confirmstate int DEFAULT 0 COMMENT  '确认状态',
qyd varchar(50) DEFAULT NULL COMMENT  '起运地',
fhrsbh varchar(50) DEFAULT NULL COMMENT  '发货人识别号',
shrsbh varchar(50) DEFAULT NULL COMMENT  '收货人识别号',
cd varchar(50) DEFAULT NULL COMMENT  '产地',
fdjhm varchar(50) DEFAULT NULL COMMENT  '发动机号码',
zh varchar(50) DEFAULT NULL COMMENT  '账号',
hgzh varchar(50) DEFAULT NULL COMMENT  '合格证号',
cjhm varchar(50) DEFAULT NULL COMMENT  '车架号码',
xcrs varchar(50) DEFAULT NULL COMMENT  '限乘人数',
yshwxx varchar(50) DEFAULT NULL COMMENT  '运输货物信息',
zyspmc varchar(50) DEFAULT NULL COMMENT  '主要商品名称',
spsm varchar(50) DEFAULT NULL COMMENT  '商品税目',
yyzzh varchar(50) DEFAULT NULL COMMENT  '营业执照号',
xfdz varchar(50) DEFAULT NULL COMMENT  '销方地址',
xfdh varchar(50) DEFAULT NULL COMMENT  '销方电话',
kpzdbs varchar(50) DEFAULT NULL COMMENT  '开票点分机号',
pdfurl varchar(50) DEFAULT NULL COMMENT  '电子发票下载地址',
imgstate int DEFAULT 0 COMMENT  '图像生成状态',
  PRIMARY KEY (`cid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


--原始测试数据表，发票详情表
DROP TABLE IF EXISTS data_warehouse.saleinvoicedetail
CREATE TABLE `saleinvoicedetail` (
	cid varchar(50) NOT NULL COMMENT  '主键',
	invoiceid varchar(50) DEFAULT NULL COMMENT  '发票GUID',
	indexno float DEFAULT NULL COMMENT  '索引序号',
	detaillistflag bit DEFAULT NULL COMMENT  '清单标志',
	invoicedetailno float DEFAULT NULL COMMENT  '发票明细序号',
	waresname varchar(50) DEFAULT NULL COMMENT  '商品名称',
	invoicelineprop int DEFAULT 0 COMMENT  '发票行性质',
	amount float DEFAULT NULL COMMENT  '金额',
	taxrate float DEFAULT NULL COMMENT  '税率',
	taxamount float DEFAULT NULL COMMENT  '税额',
	quantity float DEFAULT NULL COMMENT  '数量',
	notaxprice float DEFAULT NULL COMMENT  '不含税单价',
	taxprice float DEFAULT NULL COMMENT  '含税单价',
	taxpriceflag bit DEFAULT NULL COMMENT  '含税价标志',
	standardtype varchar(50) DEFAULT NULL COMMENT  '规格型号',
	calcunit varchar(50) DEFAULT NULL COMMENT  '计量单位',
	waresno varchar(50) DEFAULT NULL COMMENT  '商品编号',
	warestaxitem varchar(50) DEFAULT NULL COMMENT  '商品税目',
	useflag bit DEFAULT NULL COMMENT  '使用标志',
	billid varchar(50) DEFAULT NULL COMMENT  '单据ID',
  PRIMARY KEY (`cid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


--商户表
DROP TABLE IF EXISTS data_warehouse.mcht_tax;
CREATE TABLE `mcht_tax` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `mcht_cd` varchar(50) DEFAULT NULL COMMENT '商户申请编号',
  `mcht_name` varchar(150) DEFAULT NULL COMMENT '商户名称',
  `mcht_tax_cd` varchar(50) DEFAULT NULL COMMENT '商户税号（销方）',
  `mcht_addtel` varchar(150) DEFAULT NULL COMMENT '销方地址电话',
  `mcht_bankno` varchar(150) DEFAULT NULL COMMENT '销方银行帐号',
  `first_invoicedate` datetime DEFAULT NULL COMMENT '首次开票时间',
  `initial_get_flag` varchar(2) DEFAULT NULL COMMENT '初始采集完成标志位',
  `is_delete` tinyint(4) DEFAULT NULL COMMENT '逻辑删除，1.是，0.否',
  `create_time` date DEFAULT NULL COMMENT '创建时间',
  `create_user` varchar(100) DEFAULT NULL COMMENT '创建人',
  `modify_time` date DEFAULT NULL COMMENT '修改时间',
  `modify_user` varchar(100) DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (`id`),
  UNIQUE KEY `index_mcht_cd` (`mcht_cd`),
  KEY `idx_mcht_cd` (`mcht_cd`),
  KEY `idx_mcht_tax_cd` (`mcht_tax_cd`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='【税金贷】商户表';


--月统计表
DROP TABLE IF EXISTS data_warehouse.statistics_month;
CREATE TABLE `statistics_month` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `mcht_cd` varchar(50) DEFAULT NULL COMMENT '商户申请编号',
  `data_month` varchar(50) DEFAULT NULL COMMENT '统计月份',
  `invoice_sc_cnt` int(15) DEFAULT '0' COMMENT '增值税开票张数',
  `invoice_sc_cancel_cnt` int(15) DEFAULT '0' COMMENT '增值税发票作废张数',
  `invoice_sc_red_cnt` int(15) DEFAULT '0' COMMENT '增值税发票红冲张数',
  `invoice_sc_total_sum` decimal(20,2) DEFAULT '0.00' COMMENT '增值税发票合计金额税额总和',
  `invoice_cnt` int(15) DEFAULT '0' COMMENT '所有发票开票张数',
  `invoice_cr_cnt` int(15) DEFAULT '0' COMMENT '所有发票作废红冲张数',
  `invoice_amt_sum` decimal(20,2) DEFAULT '0.00' COMMENT '所有发票合计金额',
  `invoice_tax_sum` decimal(20,2) DEFAULT '0.00' COMMENT '所有发票合计税额',
  `invoice_total_sum` decimal(20,2) DEFAULT '0.00' COMMENT '所有发票合计金额税额总和',
  `invoice_cancel_cnt` int(15) DEFAULT NULL COMMENT '所有发票作废张数',
  `invoice_red_cnt` int(15) DEFAULT NULL COMMENT '所有发票红冲张数',
  `invoice_total_c_sum` decimal(20,2) DEFAULT NULL COMMENT '所有作废发票合计金额税额总和',
  `invoice_total_r_sum` decimal(20,2) DEFAULT NULL COMMENT '所有红冲发票合计金额税额总和',
  `invoice_s_cnt` int(15) DEFAULT '0' COMMENT '增值税专用发票开票张数',
  `invoice_s_cancel_cnt` int(15) DEFAULT '0' COMMENT '增值税专用发票作废张数',
  `invoice_s_red_cnt` int(15) DEFAULT '0' COMMENT '增值税专用发票红冲张数',
  `invoice_s_amt_sum` decimal(20,2) DEFAULT '0.00' COMMENT '增值税专用发票合计金额',
  `invoice_s_tax_sum` decimal(20,2) DEFAULT '0.00' COMMENT '增值税专用发票合计税额',
  `invoice_s_total_sum` decimal(20,2) DEFAULT '0.00' COMMENT '增值税专用发票合计金额税额总和',
  `invoice_c_cnt` int(15) DEFAULT '0' COMMENT '增值税普通发票开票张数',
  `invoice_c_cancel_cnt` int(15) DEFAULT '0' COMMENT '增值税普通发票作废张数',
  `invoice_c_red_cnt` int(15) DEFAULT '0' COMMENT '增值税普通发票红冲张数',
  `invoice_c_amt_sum` decimal(20,2) DEFAULT '0.00' COMMENT '增值税普通发票合计金额',
  `invoice_c_tax_sum` decimal(20,2) DEFAULT '0.00' COMMENT '增值税普通发票合计税额',
  `invoice_c_total_sum` decimal(20,2) DEFAULT '0.00' COMMENT '增值税普通发票合计金额税额总和',
  `invoice_t_cnt` int(15) DEFAULT '0' COMMENT '运输发票开票张数',
  `invoice_t_cancel_cnt` int(15) DEFAULT '0' COMMENT '运输发票作废张数',
  `invoice_t_red_cnt` int(15) DEFAULT '0' COMMENT '运输发票红冲张数',
  `invoice_t_amt_sum` decimal(20,2) DEFAULT '0.00' COMMENT '运输发票合计金额',
  `invoice_t_tax_sum` decimal(20,2) DEFAULT '0.00' COMMENT '运输发票合计税额',
  `invoice_t_total_sum` decimal(20,2) DEFAULT '0.00' COMMENT '运输发票合计金额税额总和',
  `invoice_p_cnt` int(15) DEFAULT '0' COMMENT '纸质发票开票张数',
  `invoice_p_cancel_cnt` int(15) DEFAULT '0' COMMENT '纸质发票作废张数',
  `invoice_p_red_cnt` int(15) DEFAULT '0' COMMENT '纸质发票红冲张数',
  `invoice_p_amt_sum` decimal(20,2) DEFAULT '0.00' COMMENT '纸质发票合计金额',
  `invoice_p_tax_sum` decimal(20,2) DEFAULT '0.00' COMMENT '纸质发票合计税额',
  `invoice_p_total_sum` decimal(20,2) DEFAULT '0.00' COMMENT '纸质发票合计金额税额总和',
  `invoice_e_cnt` int(15) DEFAULT '0' COMMENT '电子发票开票张数',
  `invoice_e_cancel_cnt` int(15) DEFAULT '0' COMMENT '电子发票作废张数',
  `invoice_e_red_cnt` int(15) DEFAULT '0' COMMENT '电子发票红冲张数',
  `invoice_e_amt_sum` decimal(20,2) DEFAULT '0.00' COMMENT '电子发票合计金额',
  `invoice_e_tax_sum` decimal(20,2) DEFAULT '0.00' COMMENT '电子发票合计税额',
  `invoice_e_total_sum` decimal(20,2) DEFAULT '0.00' COMMENT '电子发票合计金额税额总和',
  `invoice_r_cnt` int(15) DEFAULT '0' COMMENT '卷式发票开票张数',
  `invoice_r_cancel_cnt` int(15) DEFAULT '0' COMMENT '卷式发票作废张数',
  `invoice_r_red_cnt` int(15) DEFAULT '0' COMMENT '卷式发票红冲张数',
  `invoice_r_amt_sum` decimal(20,2) DEFAULT '0.00' COMMENT '卷式发票合计金额',
  `invoice_r_tax_sum` decimal(20,2) DEFAULT '0.00' COMMENT '卷式发票合计税额',
  `invoice_r_total_sum` decimal(20,2) DEFAULT '0.00' COMMENT '卷式发票合计金额税额总和',
  `invoice_red_cnt_rate` decimal(20,2) DEFAULT '0.00' COMMENT '红冲发票张数占比',
  `invoice_cancel_cnt_rate` decimal(20,2) DEFAULT '0.00' COMMENT '作废发票张数占比',
  `invoice_red_total_sum_rate` decimal(20,2) DEFAULT '0.00' COMMENT '红冲发票合计金额税额总和比率',
  `invoice_cancel_total_sum_rate` decimal(20,2) DEFAULT '0.00' COMMENT '作废发票合计金额税金总和比率',
  `invoice_lt100_cnt` int(15) DEFAULT '0' COMMENT '金额小于100发票张数',
  `invoice_lt100_cr_cnt` int(15) DEFAULT '0' COMMENT '金额小于100发票作废红冲张数',
  `invoice_lt100_total_sum` decimal(20,2) DEFAULT '0.00' COMMENT '金额小于100发票合计金额税额总和',
  `invoice_lt1000_cnt` int(15) DEFAULT '0' COMMENT '金额小于1000（且大于等于100）发票张数',
  `invoice_lt1000_cr_cnt` int(15) DEFAULT '0' COMMENT '金额小于1000（且大于等于100）发票作废红冲张数',
  `invoice_lt1000_total_sum` decimal(20,2) DEFAULT '0.00' COMMENT '金额小于1000（且大约等于100）发票合计金额税额总和',
  `invoice_lt2500_cnt` int(15) DEFAULT '0' COMMENT '金额小于2500（且大于等于1000）发票张数',
  `invoice_lt2500_cr_cnt` int(15) DEFAULT '0' COMMENT '金额小于2500（且大于等于1000）发票作废红冲张数',
  `invoice_lt2500_total_sum` decimal(20,2) DEFAULT '0.00' COMMENT '金额小于2500（且大于等于1000）发票合计金额税额总和',
  `invoice_lt5000_cnt` int(15) DEFAULT '0' COMMENT '金额小于5000（且大于等于2500）发票张数',
  `invoice_lt5000_cr_cnt` int(15) DEFAULT '0' COMMENT '金额小于5000（且大于等于2500）发票作废红冲张数',
  `invoice_lt5000_total_sum` decimal(20,2) DEFAULT '0.00' COMMENT '金额小于5000（且大于等于2500）发票合计金额税额总和',
  `invoice_lt10000_cnt` int(15) DEFAULT '0' COMMENT '金额小于10000（且大于等于5000）发票张数',
  `invoice_lt10000_cr_cnt` int(15) DEFAULT '0' COMMENT '金额小于10000（且大于等于5000）发票作废红冲张数',
  `invoice_lt10000_total_sum` decimal(20,2) DEFAULT '0.00' COMMENT '金额小于10000（且大于等于5000）发票合计金额税额总和',
  `invoice_gt10000_cnt` int(15) DEFAULT '0' COMMENT '金额大于10000发票张数',
  `invoice_gt10000_cr_cnt` int(15) DEFAULT '0' COMMENT '金额大于10000发票作废红冲张数',
  `invoice_gt10000_total_sum` decimal(20,2) DEFAULT '0.00' COMMENT '金额大于10000发票合计金额税额总和',
  `invoice_detail_cnt` int(15) DEFAULT '0' COMMENT '附有清单的发票张数',
  `invoice_detail_cr_cnt` int(15) DEFAULT '0' COMMENT '附有清单的发票作废红冲张数',
  `invoice_detail_total_sum` decimal(20,2) DEFAULT '0.00' COMMENT '附有清单的发票合计金额税额总和',
  `buyer_cnt` int(15) DEFAULT '0' COMMENT '统计月交易对手数目',
  `buyer_cnt_all` int(15) DEFAULT '0' COMMENT '截至统计月所有交易对手数目',
  `buyer_a_cnt` int(15) DEFAULT '0' COMMENT '在统计月归为A类的交易对手数目',
  `buyer_b_cnt` int(15) DEFAULT '0' COMMENT '在统计月归为B类的交易对手数目',
  `buyer_c_cnt` int(15) DEFAULT '0' COMMENT '在统计月归为C类的交易对手数目',
  `buyer_f_cnt` int(15) DEFAULT '0' COMMENT '在统计月归为F类的交易对手数目',
  `is_delete` tinyint(4) DEFAULT NULL COMMENT '逻辑删除，1.是，0.否',
  `create_time` date DEFAULT NULL COMMENT '创建时间',
  `create_user` varchar(100) DEFAULT NULL COMMENT '创建人',
  `modify_time` date DEFAULT NULL COMMENT '修改时间',
  `modify_user` varchar(100) DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (`id`),
  UNIQUE KEY `index_unique` (`mcht_cd`,`data_month`),
  KEY `idx_mcht_cd_data_month` (`mcht_cd`,`data_month`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='【税金贷】月统计表';





--跨月统计表
DROP TABLE IF EXISTS data_warehouse.statistics_crossmonth;

CREATE TABLE `statistics_crossmonth` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `mcht_cd` varchar(50) DEFAULT NULL COMMENT '商户申请编号',
  `data_month` varchar(50) DEFAULT NULL COMMENT '统计月份',
  `invoice_sc_cnt_l3m` int(15) DEFAULT '0' COMMENT '近3月增值税开票张数',
  `invoice_sc_cancel_cnt_l3m` int(15) DEFAULT '0' COMMENT '近3月增值税发票作废张数',
  `invoice_sc_red_cnt_l3m` int(15) DEFAULT '0' COMMENT '近3月增值税发票红冲张数',
  `invoice_sc_total_sum_l3m` decimal(20,2) DEFAULT '0.00' COMMENT '近3月增值税发票合计金额税额总和',
  `invoice_cnt_l3m` int(15) DEFAULT '0' COMMENT '近3月所有发票开票张数',
  `invoice_cr_cnt_l3m` int(15) DEFAULT '0' COMMENT '近3月所有发票作废红冲张数',
  `invoice_total_sum_l3m` decimal(20,2) DEFAULT '0.00' COMMENT '近3月所有发票合计金额税额总和',
  `invoice_s_cnt_l3m` int(15) DEFAULT '0' COMMENT '近3月增值税专用发票开票张数',
  `invoice_s_cancel_cnt_l3m` int(15) DEFAULT '0' COMMENT '近3月增值税专用发票作废张数',
  `invoice_s_red_cnt_l3m` int(15) DEFAULT '0' COMMENT '近3月增值税专用发票红冲张数',
  `invoice_s_total_sum_l3m` decimal(20,2) DEFAULT '0.00' COMMENT '近3月增值税专用发票合计金额税额总和',
  `invoice_c_cnt_l3m` int(15) DEFAULT '0' COMMENT '近3月增值税普通发票开票张数',
  `invoice_c_cancel_cnt_l3m` int(15) DEFAULT '0' COMMENT '近3月增值税普通发票作废张数',
  `invoice_c_red_cnt_l3m` int(15) DEFAULT '0' COMMENT '近3月增值税普通发票红冲张数',
  `invoice_c_total_sum_l3m` decimal(20,2) DEFAULT '0.00' COMMENT '近3月增值税普通发票合计金额税额总和',
  `invoice_t_cnt_l3m` int(15) DEFAULT '0' COMMENT '近3月运输发票开票张数',
  `invoice_t_cancel_cnt_l3m` int(15) DEFAULT '0' COMMENT '近3月运输发票作废张数',
  `invoice_t_red_cnt_l3m` int(15) DEFAULT '0' COMMENT '近3月运输发票红冲张数',
  `invoice_t_total_sum_l3m` decimal(20,2) DEFAULT '0.00' COMMENT '近3月运输发票合计金额税额总和',
  `invoice_p_cnt_l3m` int(15) DEFAULT '0' COMMENT '近3月纸质发票开票张数',
  `invoice_p_cancel_cnt_l3m` int(15) DEFAULT '0' COMMENT '近3月纸质发票作废张数',
  `invoice_p_red_cnt_l3m` int(15) DEFAULT '0' COMMENT '近3月纸质发票红冲张数',
  `invoice_p_total_sum_l3m` decimal(20,2) DEFAULT '0.00' COMMENT '近3月纸质发票合计金额税额总和',
  `invoice_e_cnt_l3m` int(15) DEFAULT '0' COMMENT '近3月电子发票开票张数',
  `invoice_e_cancel_cnt_l3m` int(15) DEFAULT '0' COMMENT '近3月电子发票作废张数',
  `invoice_e_red_cnt_l3m` int(15) DEFAULT '0' COMMENT '近3月电子发票红冲张数',
  `invoice_e_total_sum_l3m` decimal(20,2) DEFAULT '0.00' COMMENT '近3月电子发票合计金额税额总和',
  `invoice_r_cnt_l3m` int(15) DEFAULT '0' COMMENT '近3月卷式发票开票张数',
  `invoice_r_cancel_cnt_l3m` int(15) DEFAULT '0' COMMENT '近3月卷式发票作废张数',
  `invoice_r_red_cnt_l3m` int(15) DEFAULT '0' COMMENT '近3月卷式发票红冲张数',
  `invoice_r_total_sum_l3m` decimal(20,2) DEFAULT '0.00' COMMENT '近3月卷式发票合计金额税额总和',
  `invoice_red_cnt_rate_l3m` decimal(20,2) DEFAULT '0.00' COMMENT '近3月红冲发票张数占比',
  `invoice_cancel_cnt_rate_l3m` decimal(20,2) DEFAULT '0.00' COMMENT '近3月作废发票张数占比',
  `invoice_red_total_sum_rate_l3m` decimal(20,2) DEFAULT '0.00' COMMENT '近3月红冲发票合计金额税额总和比率',
  `invoice_cancel_total_sum_rate_l3m` decimal(20,2) DEFAULT '0.00' COMMENT '近3月作废发票合计金额税金总和比率',
  `invoice_lt100_cnt_l3m` int(15) DEFAULT '0' COMMENT '近3月金额小于100发票张数',
  `invoice_lt100_cr_cnt_l3m` int(15) DEFAULT '0' COMMENT '近3月金额小于100发票作废红冲张数',
  `invoice_lt100_total_sum_l3m` decimal(20,2) DEFAULT '0.00' COMMENT '近3月金额小于100发票合计金额税额总和',
  `invoice_lt1000_cnt_l3m` int(15) DEFAULT '0' COMMENT '近3月金额小于1000（且大于等于100）发票张数',
  `invoice_lt1000_cr_cnt_l3m` int(15) DEFAULT '0' COMMENT '近3月金额小于1000（且大于等于100）发票作废红冲张数',
  `invoice_lt1000_total_sum_l3m` decimal(20,2) DEFAULT '0.00' COMMENT '近3月金额小于1000（且大于等于100）发票合计金额税额总和',
  `invoice_lt2500_cnt_l3m` int(15) DEFAULT '0' COMMENT '近3月金额小于2500且（且大于等于1000）发票张数',
  `invoice_lt2500_cr_cnt_l3m` int(15) DEFAULT '0' COMMENT '近3月金额小于2500（且大于等于1000）发票作废红冲张数',
  `invoice_lt2500_total_sum_l3m` decimal(20,2) DEFAULT '0.00' COMMENT '近3月金额小于2500（且大于等于1000）发票合计金额税额总和',
  `invoice_lt5000_cnt_l3m` int(15) DEFAULT '0' COMMENT '近3月金额小于5000（且大于等于2500）发票张数',
  `invoice_lt5000_cr_cnt_l3m` int(15) DEFAULT '0' COMMENT '近3月金额小于5000（且大于等于2500）发票作废红冲张数',
  `invoice_lt5000_total_sum_l3m` decimal(20,2) DEFAULT '0.00' COMMENT '近3月金额小于5000（且大于等于2500）发票合计金额税额总和',
  `invoice_lt10000_cnt_l3m` int(15) DEFAULT '0' COMMENT '近3月金额小于10000（且大于等于5000）发票张数',
  `invoice_lt10000_cr_cnt_l3m` int(15) DEFAULT '0' COMMENT '近3月金额小于10000（且大于等于5000）发票作废红冲张数',
  `invoice_lt10000_total_sum_l3m` decimal(20,2) DEFAULT '0.00' COMMENT '近3月金额小于10000（且大于等于5000）发票合计金额税额总和',
  `invoice_gt10000_cnt_l3m` int(15) DEFAULT '0' COMMENT '近3月金额大于10000发票张数',
  `invoice_gt10000_cr_cnt_l3m` int(15) DEFAULT '0' COMMENT '近3月金额大于10000发票作废红冲张数',
  `invoice_gt10000_total_sum_l3m` decimal(20,2) DEFAULT '0.00' COMMENT '近3月金额大于10000发票合计金额税额总和',
  `invoice_detail_cnt_l3m` int(15) DEFAULT '0' COMMENT '近3月附有清单的发票张数',
  `invoice_detail_cr_cnt_l3m` int(15) DEFAULT '0' COMMENT '近3月附有清单的发票作废红冲张数',
  `invoice_detail_total_sum_l3m` decimal(20,2) DEFAULT '0.00' COMMENT '近3月附有清单的发票合计金额税额总和',
  `buyer_cnt_l3m` int(15) DEFAULT '0' COMMENT '近3月交易对手数目',
  `invoice_sc_cnt_l6m` int(15) DEFAULT '0' COMMENT '近6月增值税开票张数',
  `invoice_sc_cancel_cnt_l6m` int(15) DEFAULT '0' COMMENT '近6月增值税发票作废张数',
  `invoice_sc_red_cnt_l6m` int(15) DEFAULT '0' COMMENT '近6月增值税发票红冲张数',
  `invoice_sc_total_sum_l6m` decimal(20,2) DEFAULT '0.00' COMMENT '近6月增值税发票合计金额税额总和',
  `invoice_cnt_l6m` int(15) DEFAULT '0' COMMENT '近6月所有发票开票张数',
  `invoice_cr_cnt_l6m` int(15) DEFAULT '0' COMMENT '近6月所有发票作废红冲张数',
  `invoice_total_sum_l6m` decimal(20,2) DEFAULT '0.00' COMMENT '近6月所有发票合计金额税额总和',
  `invoice_s_cnt_l6m` int(15) DEFAULT '0' COMMENT '近6月增值税专用发票开票张数',
  `invoice_s_cancel_cnt_l6m` int(15) DEFAULT '0' COMMENT '近6月增值税专用发票作废张数',
  `invoice_s_red_cnt_l6m` int(15) DEFAULT '0' COMMENT '近6月增值税专用发票红冲张数',
  `invoice_s_total_sum_l6m` decimal(20,2) DEFAULT '0.00' COMMENT '近6月增值税专用发票合计金额税额总和',
  `invoice_c_cnt_l6m` int(15) DEFAULT '0' COMMENT '近6月增值税普通发票开票张数',
  `invoice_c_cancel_cnt_l6m` int(15) DEFAULT '0' COMMENT '近6月增值税普通发票作废张数',
  `invoice_c_red_cnt_l6m` int(15) DEFAULT '0' COMMENT '近6月增值税普通发票红冲张数',
  `invoice_c_total_sum_l6m` decimal(20,2) DEFAULT '0.00' COMMENT '近6月增值税普通发票合计金额税额总和',
  `invoice_t_cnt_l6m` int(15) DEFAULT '0' COMMENT '近6月运输发票开票张数',
  `invoice_t_cancel_cnt_l6m` int(15) DEFAULT '0' COMMENT '近6月运输发票作废张数',
  `invoice_t_red_cnt_l6m` int(15) DEFAULT '0' COMMENT '近6月运输发票红冲张数',
  `invoice_t_total_sum_l6m` decimal(20,2) DEFAULT '0.00' COMMENT '近6月运输发票合计金额税额总和',
  `invoice_p_cnt_l6m` int(15) DEFAULT '0' COMMENT '近6月纸质发票开票张数',
  `invoice_p_cancel_cnt_l6m` int(15) DEFAULT '0' COMMENT '近6月纸质发票作废张数',
  `invoice_p_red_cnt_l6m` int(15) DEFAULT '0' COMMENT '近6月纸质发票红冲张数',
  `invoice_p_total_sum_l6m` decimal(20,2) DEFAULT '0.00' COMMENT '近6月纸质发票合计金额税额总和',
  `invoice_e_cnt_l6m` int(15) DEFAULT '0' COMMENT '近6月电子发票开票张数',
  `invoice_e_cancel_cnt_l6m` int(15) DEFAULT '0' COMMENT '近6月电子发票作废张数',
  `invoice_e_red_cnt_l6m` int(15) DEFAULT '0' COMMENT '近6月电子发票红冲张数',
  `invoice_e_total_sum_l6m` decimal(20,2) DEFAULT '0.00' COMMENT '近6月电子发票合计金额税额总和',
  `invoice_r_cnt_l6m` int(15) DEFAULT '0' COMMENT '近6月卷式发票开票张数',
  `invoice_r_cancel_cnt_l6m` int(15) DEFAULT '0' COMMENT '近6月卷式发票作废张数',
  `invoice_r_red_cnt_l6m` int(15) DEFAULT '0' COMMENT '近6月卷式发票红冲张数',
  `invoice_r_total_sum_l6m` decimal(20,2) DEFAULT '0.00' COMMENT '近6月卷式发票合计金额税额总和',
  `invoice_red_cnt_rate_l6m` decimal(20,2) DEFAULT '0.00' COMMENT '近6月红冲发票张数占比',
  `invoice_cancel_cnt_rate_l6m` decimal(20,2) DEFAULT '0.00' COMMENT '近6月作废发票张数占比',
  `invoice_red_total_sum_rate_l6m` decimal(20,2) DEFAULT '0.00' COMMENT '近6月红冲发票合计金额税额总和比率',
  `invoice_cancel_total_sum_rate_l6m` decimal(20,2) DEFAULT '0.00' COMMENT '近6月作废发票合计金额税金总和比率',
  `invoice_lt100_cnt_l6m` int(15) DEFAULT '0' COMMENT '近6月金额小于100发票张数',
  `invoice_lt100_cr_cnt_l6m` int(15) DEFAULT '0' COMMENT '近6月金额小于100发票作废红冲张数',
  `invoice_lt100_total_sum_l6m` decimal(20,2) DEFAULT '0.00' COMMENT '近6月金额小于100发票合计金额税额总和',
  `invoice_lt1000_cnt_l6m` int(15) DEFAULT '0' COMMENT '近6月金额小于1000（且大于等于100）发票张数',
  `invoice_lt1000_cr_cnt_l6m` int(15) DEFAULT '0' COMMENT '近6月金额小于1000（且大于等于100）发票作废红冲张数',
  `invoice_lt1000_total_sum_l6m` decimal(20,2) DEFAULT '0.00' COMMENT '近6月金额小于1000（且大于等于100）发票合计金额税额总和',
  `invoice_lt2500_cnt_l6m` int(15) DEFAULT '0' COMMENT '近6月金额小于2500且（且大于等于1000）发票张数',
  `invoice_lt2500_cr_cnt_l6m` int(15) DEFAULT '0' COMMENT '近6月金额小于2500（且大于等于1000）发票作废红冲张数',
  `invoice_lt2500_total_sum_l6m` decimal(20,2) DEFAULT '0.00' COMMENT '近6月金额小于2500（且大于等于1000）发票合计金额税额总和',
  `invoice_lt5000_cnt_l6m` int(15) DEFAULT '0' COMMENT '近6月金额小于5000（且大于等于2500）发票张数',
  `invoice_lt5000_cr_cnt_l6m` int(15) DEFAULT '0' COMMENT '近6月金额小于5000（且大于等于2500）发票作废红冲张数',
  `invoice_lt5000_total_sum_l6m` decimal(20,2) DEFAULT '0.00' COMMENT '近6月金额小于5000（且大于等于2500）发票合计金额税额总和',
  `invoice_lt10000_cnt_l6m` int(15) DEFAULT '0' COMMENT '近6月金额小于10000（且大于等于5000）发票张数',
  `invoice_lt10000_cr_cnt_l6m` int(15) DEFAULT '0' COMMENT '近6月金额小于10000（且大于等于5000）发票作废红冲张数',
  `invoice_lt10000_total_sum_l6m` decimal(20,2) DEFAULT '0.00' COMMENT '近6月金额小于10000（且大于等于5000）发票合计金额税额总和',
  `invoice_gt10000_cnt_l6m` int(15) DEFAULT '0' COMMENT '近6月金额大于10000发票张数',
  `invoice_gt10000_cr_cnt_l6m` int(15) DEFAULT '0' COMMENT '近6月金额大于10000发票作废红冲张数',
  `invoice_gt10000_total_sum_l6m` decimal(20,2) DEFAULT '0.00' COMMENT '近6月金额大于10000发票合计金额税额总和',
  `invoice_detail_cnt_l6m` int(15) DEFAULT '0' COMMENT '近6月附有清单的发票张数',
  `invoice_detail_cr_cnt_l6m` int(15) DEFAULT '0' COMMENT '近6月附有清单的发票作废红冲张数',
  `invoice_detail_total_sum_l6m` decimal(20,2) DEFAULT '0.00' COMMENT '近6月附有清单的发票合计金额税额总和',
  `buyer_cnt_l6m` int(15) DEFAULT '0' COMMENT '近6月交易对手数目',
  `buyer_a_invoice_cnt_l6m` int(15) DEFAULT '0' COMMENT '在统计月归为A类的交易对手近6月开票张数',
  `buyer_b_invoice_cnt_l6m` int(15) DEFAULT '0' COMMENT '在统计月归为B类的交易对手近6月开票张数',
  `buyer_c_invoice_cnt_l6m` int(15) DEFAULT '0' COMMENT '在统计月归为C类的交易对手近6月开票张数',
  `buyer_f_invoice_cnt_l6m` int(15) DEFAULT '0' COMMENT '在统计月归为F类的交易对手近6月开票张数',
  `buyer_a_amt_sum_l6m` decimal(20,2) DEFAULT '0.00' COMMENT '在统计月归为A类的交易对手近6月合计金额总和',
  `buyer_b_amt_sum_l6m` decimal(20,2) DEFAULT '0.00' COMMENT '在统计月归为B类的交易对手近6月合计金额总和',
  `buyer_c_amt_sum_l6m` decimal(20,2) DEFAULT '0.00' COMMENT '在统计月归为C类的交易对手近6月合计金额总和',
  `buyer_f_amt_sum_l6m` decimal(20,2) DEFAULT '0.00' COMMENT '在统计月归为F类的交易对手近6月合计金额总和',
  `invoice_sc_cnt_l12m` int(15) DEFAULT '0' COMMENT '近12月增值税开票张数',
  `invoice_sc_cancel_cnt_l12m` int(15) DEFAULT '0' COMMENT '近12月增值税发票作废张数',
  `invoice_sc_red_cnt_l12m` int(15) DEFAULT '0' COMMENT '近12月增值税发票红冲张数',
  `invoice_sc_total_sum_l12m` decimal(20,2) DEFAULT '0.00' COMMENT '近12月增值税发票合计金额税额总和',
  `invoice_cnt_l12m` int(15) DEFAULT '0' COMMENT '近12月所有发票开票张数',
  `invoice_cr_cnt_l12m` int(15) DEFAULT '0' COMMENT '近12月所有发票作废红冲张数',
  `invoice_total_sum_l12m` decimal(20,2) DEFAULT '0.00' COMMENT '近12月所有发票合计金额税额总和',
  `invoice_s_cnt_l12m` int(15) DEFAULT '0' COMMENT '近12月增值税专用发票开票张数',
  `invoice_s_cancel_cnt_l12m` int(15) DEFAULT '0' COMMENT '近12月增值税专用发票作废张数',
  `invoice_s_red_cnt_l12m` int(15) DEFAULT '0' COMMENT '近12月增值税专用发票红冲张数',
  `invoice_s_total_sum_l12m` decimal(20,2) DEFAULT '0.00' COMMENT '近12月增值税专用发票合计金额税额总和',
  `invoice_c_cnt_l12m` int(15) DEFAULT '0' COMMENT '近12月增值税普通发票开票张数',
  `invoice_c_cancel_cnt_l12m` int(15) DEFAULT '0' COMMENT '近12月增值税普通发票作废张数',
  `invoice_c_red_cnt_l12m` int(15) DEFAULT '0' COMMENT '近12月增值税普通发票红冲张数',
  `invoice_c_total_sum_l12m` decimal(20,2) DEFAULT '0.00' COMMENT '近12月增值税普通发票合计金额税额总和',
  `invoice_t_cnt_l12m` int(15) DEFAULT '0' COMMENT '近12月运输发票开票张数',
  `invoice_t_cancel_cnt_l12m` int(15) DEFAULT '0' COMMENT '近12月运输发票作废张数',
  `invoice_t_red_cnt_l12m` int(15) DEFAULT '0' COMMENT '近12月运输发票红冲张数',
  `invoice_t_total_sum_l12m` decimal(20,2) DEFAULT '0.00' COMMENT '近12月运输发票合计金额税额总和',
  `invoice_p_cnt_l12m` int(15) DEFAULT '0' COMMENT '近12月纸质发票开票张数',
  `invoice_p_cancel_cnt_l12m` int(15) DEFAULT '0' COMMENT '近12月纸质发票作废张数',
  `invoice_p_red_cnt_l12m` int(15) DEFAULT '0' COMMENT '近12月纸质发票红冲张数',
  `invoice_p_total_sum_l12m` decimal(20,2) DEFAULT '0.00' COMMENT '近12月纸质发票合计金额税额总和',
  `invoice_e_cnt_l12m` int(15) DEFAULT '0' COMMENT '近12月电子发票开票张数',
  `invoice_e_cancel_cnt_l12m` int(15) DEFAULT '0' COMMENT '近12月电子发票作废张数',
  `invoice_e_red_cnt_l12m` int(15) DEFAULT '0' COMMENT '近12月电子发票红冲张数',
  `invoice_e_total_sum_l12m` decimal(20,2) DEFAULT '0.00' COMMENT '近12月电子发票合计金额税额总和',
  `invoice_r_cnt_l12m` int(15) DEFAULT '0' COMMENT '近12月卷式发票开票张数',
  `invoice_r_cancel_cnt_l12m` int(15) DEFAULT '0' COMMENT '近12月卷式发票作废张数',
  `invoice_r_red_cnt_l12m` int(15) DEFAULT '0' COMMENT '近12月卷式发票红冲张数',
  `invoice_r_total_sum_l12m` decimal(20,2) DEFAULT '0.00' COMMENT '近12月卷式发票合计金额税额总和',
  `invoice_red_cnt_rate_l12m` decimal(20,2) DEFAULT '0.00' COMMENT '近12月红冲发票张数占比',
  `invoice_cancel_cnt_rate_l12m` decimal(20,2) DEFAULT '0.00' COMMENT '近12月作废发票张数占比',
  `invoice_red_total_sum_rate_l12m` decimal(20,2) DEFAULT '0.00' COMMENT '近12月红冲发票合计金额税额总和比率',
  `invoice_cancel_total_sum_rate_l12m` decimal(20,2) DEFAULT '0.00' COMMENT '近12月作废发票合计金额税金总和比率',
  `invoice_lt100_cnt_l12m` int(15) DEFAULT '0' COMMENT '近12月金额小于100发票张数',
  `invoice_lt100_cr_cnt_l12m` int(15) DEFAULT '0' COMMENT '近12月金额小于100发票作废红冲张数',
  `invoice_lt100_total_sum_l12m` decimal(20,2) DEFAULT '0.00' COMMENT '近12月金额小于100发票合计金额税额总和',
  `invoice_lt1000_cnt_l12m` int(15) DEFAULT '0' COMMENT '近12月金额小于1000（且大于等于100）发票张数',
  `invoice_lt1000_cr_cnt_l12m` int(15) DEFAULT '0' COMMENT '近12月金额小于1000（且大于等于100）发票作废红冲张数',
  `invoice_lt1000_total_sum_l12m` decimal(20,2) DEFAULT '0.00' COMMENT '近12月金额小于1000（且大于等于100）发票合计金额税额总和',
  `invoice_lt2500_cnt_l12m` int(15) DEFAULT '0' COMMENT '近12月金额小于2500且（且大于等于1000）发票张数',
  `invoice_lt2500_cr_cnt_l12m` int(15) DEFAULT '0' COMMENT '近12月金额小于2500（且大于等于1000）发票作废红冲张数',
  `invoice_lt2500_total_sum_l12m` decimal(20,2) DEFAULT '0.00' COMMENT '近12月金额小于2500（且大于等于1000）发票合计金额税额总和',
  `invoice_lt5000_cnt_l12m` int(15) DEFAULT '0' COMMENT '近12月金额小于5000（且大于等于2500）发票张数',
  `invoice_lt5000_cr_cnt_l12m` int(15) DEFAULT '0' COMMENT '近12月金额小于5000（且大于等于2500）发票作废红冲张数',
  `invoice_lt5000_total_sum_l12m` decimal(20,2) DEFAULT '0.00' COMMENT '近12月金额小于5000（且大于等于2500）发票合计金额税额总和',
  `invoice_lt10000_cnt_l12m` int(15) DEFAULT '0' COMMENT '近12月金额小于10000（且大于等于5000）发票张数',
  `invoice_lt10000_cr_cnt_l12m` int(15) DEFAULT '0' COMMENT '近12月金额小于10000（且大于等于5000）发票作废红冲张数',
  `invoice_lt10000_total_sum_l12m` decimal(20,2) DEFAULT '0.00' COMMENT '近12月金额小于10000（且大于等于5000）发票合计金额税额总和',
  `invoice_gt10000_cnt_l12m` int(15) DEFAULT '0' COMMENT '近12月金额大于10000发票张数',
  `invoice_gt10000_cr_cnt_l12m` int(15) DEFAULT '0' COMMENT '近12月金额大于10000发票作废红冲张数',
  `invoice_gt10000_total_sum_l12m` decimal(20,2) DEFAULT '0.00' COMMENT '近12月金额大于10000发票合计金额税额总和',
  `invoice_detail_cnt_l12m` int(15) DEFAULT '0' COMMENT '近12月附有清单的发票张数',
  `invoice_detail_cr_cnt_l12m` int(15) DEFAULT '0' COMMENT '近12月附有清单的发票作废红冲张数',
  `invoice_detail_total_sum_l12m` decimal(20,2) DEFAULT '0.00' COMMENT '近12月附有清单的发票合计金额税额总和',
  `buyer_cnt_l12m` int(15) DEFAULT '0' COMMENT '近12月交易对手数目',
  `buyer_a_invoice_cnt_l12m` int(15) DEFAULT '0' COMMENT '在统计月归为A类的交易对手近12月开票张数',
  `buyer_b_invoice_cnt_l12m` int(15) DEFAULT '0' COMMENT '在统计月归为B类的交易对手近12月开票张数',
  `buyer_c_invoice_cnt_l12m` int(15) DEFAULT '0' COMMENT '在统计月归为C类的交易对手近12月开票张数',
  `buyer_f_invoice_cnt_l12m` int(15) DEFAULT '0' COMMENT '在统计月归为F类的交易对手近12月开票张数',
  `buyer_a_amt_sum_l12m` decimal(20,2) DEFAULT '0.00' COMMENT '在统计月归为A类的交易对手近12月合计金额总和',
  `buyer_b_amt_sum_l12m` decimal(20,2) DEFAULT '0.00' COMMENT '在统计月归为B类的交易对手近12月合计金额总和',
  `buyer_c_amt_sum_l12m` decimal(20,2) DEFAULT '0.00' COMMENT '在统计月归为C类的交易对手近12月合计金额总和',
  `buyer_f_amt_sum_l12m` decimal(20,2) DEFAULT '0.00' COMMENT '在统计月归为F类的交易对手近12月合计金额总和',
  `invoice_sc_cnt_l24m` int(15) DEFAULT '0' COMMENT '近24月增值税开票张数',
  `invoice_sc_cancel_cnt_l24m` int(15) DEFAULT '0' COMMENT '近24月增值税发票作废张数',
  `invoice_sc_red_cnt_l24m` int(15) DEFAULT '0' COMMENT '近24月增值税发票红冲张数',
  `invoice_sc_total_sum_l24m` decimal(20,2) DEFAULT '0.00' COMMENT '近24月增值税发票合计金额税额总和',
  `invoice_cnt_l24m` int(15) DEFAULT '0' COMMENT '近24月所有发票开票张数',
  `invoice_cr_cnt_l24m` int(15) DEFAULT '0' COMMENT '近24月所有发票作废红冲张数',
  `invoice_total_sum_l24m` decimal(20,2) DEFAULT '0.00' COMMENT '近24月所有发票合计金额税额总和',
  `invoice_s_cnt_l24m` int(15) DEFAULT '0' COMMENT '近24月增值税专用发票开票张数',
  `invoice_s_cancel_cnt_l24m` int(15) DEFAULT '0' COMMENT '近24月增值税专用发票作废张数',
  `invoice_s_red_cnt_l24m` int(15) DEFAULT '0' COMMENT '近24月增值税专用发票红冲张数',
  `invoice_s_total_sum_l24m` decimal(20,2) DEFAULT '0.00' COMMENT '近24月增值税专用发票合计金额税额总和',
  `invoice_c_cnt_l24m` int(15) DEFAULT '0' COMMENT '近24月增值税普通发票开票张数',
  `invoice_c_cancel_cnt_l24m` int(15) DEFAULT '0' COMMENT '近24月增值税普通发票作废张数',
  `invoice_c_red_cnt_l24m` int(15) DEFAULT '0' COMMENT '近24月增值税普通发票红冲张数',
  `invoice_c_total_sum_l24m` decimal(20,2) DEFAULT '0.00' COMMENT '近24月增值税普通发票合计金额税额总和',
  `invoice_t_cnt_l24m` int(15) DEFAULT '0' COMMENT '近24月运输发票开票张数',
  `invoice_t_cancel_cnt_l24m` int(15) DEFAULT '0' COMMENT '近24月运输发票作废张数',
  `invoice_t_red_cnt_l24m` int(15) DEFAULT '0' COMMENT '近24月运输发票红冲张数',
  `invoice_t_total_sum_l24m` decimal(20,2) DEFAULT '0.00' COMMENT '近24月运输发票合计金额税额总和',
  `invoice_p_cnt_l24m` int(15) DEFAULT '0' COMMENT '近24月纸质发票开票张数',
  `invoice_p_cancel_cnt_l24m` int(15) DEFAULT '0' COMMENT '近24月纸质发票作废张数',
  `invoice_p_red_cnt_l24m` int(15) DEFAULT '0' COMMENT '近24月纸质发票红冲张数',
  `invoice_p_total_sum_l24m` decimal(20,2) DEFAULT '0.00' COMMENT '近24月纸质发票合计金额税额总和',
  `invoice_e_cnt_l24m` int(15) DEFAULT '0' COMMENT '近24月电子发票开票张数',
  `invoice_e_cancel_cnt_l24m` int(15) DEFAULT '0' COMMENT '近24月电子发票作废张数',
  `invoice_e_red_cnt_l24m` int(15) DEFAULT '0' COMMENT '近24月电子发票红冲张数',
  `invoice_e_total_sum_l24m` decimal(20,2) DEFAULT '0.00' COMMENT '近24月电子发票合计金额税额总和',
  `invoice_r_cnt_l24m` int(15) DEFAULT '0' COMMENT '近24月卷式发票开票张数',
  `invoice_r_cancel_cnt_l24m` int(15) DEFAULT '0' COMMENT '近24月卷式发票作废张数',
  `invoice_r_red_cnt_l24m` int(15) DEFAULT '0' COMMENT '近24月卷式发票红冲张数',
  `invoice_r_total_sum_l24m` decimal(20,2) DEFAULT '0.00' COMMENT '近24月卷式发票合计金额税额总和',
  `invoice_red_cnt_rate_l24m` decimal(20,2) DEFAULT '0.00' COMMENT '近24月红冲发票张数占比',
  `invoice_cancel_cnt_rate_l24m` decimal(20,2) DEFAULT '0.00' COMMENT '近24月作废发票张数占比',
  `invoice_red_total_sum_rate_l24m` decimal(20,2) DEFAULT '0.00' COMMENT '近24月红冲发票合计金额税额总和比率',
  `invoice_cancel_total_sum_rate_l24m` decimal(20,2) DEFAULT '0.00' COMMENT '近24月作废发票合计金额税金总和比率',
  `invoice_lt100_cnt_l24m` int(15) DEFAULT '0' COMMENT '近24月金额小于100发票张数',
  `invoice_lt100_cr_cnt_l24m` int(15) DEFAULT '0' COMMENT '近24月金额小于100发票作废红冲张数',
  `invoice_lt100_total_sum_l24m` decimal(20,2) DEFAULT '0.00' COMMENT '近24月金额小于100发票合计金额税额总和',
  `invoice_lt1000_cnt_l24m` int(15) DEFAULT '0' COMMENT '近24月金额小于1000（且大于等于100）发票张数',
  `invoice_lt1000_cr_cnt_l24m` int(15) DEFAULT '0' COMMENT '近24月金额小于1000（且大于等于100）发票作废红冲张数',
  `invoice_lt1000_total_sum_l24m` decimal(20,2) DEFAULT '0.00' COMMENT '近24月金额小于1000（且大于等于100）发票合计金额税额总和',
  `invoice_lt2500_cnt_l24m` int(15) DEFAULT '0' COMMENT '近24月金额小于2500且（且大于等于1000）发票张数',
  `invoice_lt2500_cr_cnt_l24m` int(15) DEFAULT '0' COMMENT '近24月金额小于2500（且大于等于1000）发票作废红冲张数',
  `invoice_lt2500_total_sum_l24m` decimal(20,2) DEFAULT '0.00' COMMENT '近24月金额小于2500（且大于等于1000）发票合计金额税额总和',
  `invoice_lt5000_cnt_l24m` int(15) DEFAULT '0' COMMENT '近24月金额小于5000（且大于等于2500）发票张数',
  `invoice_lt5000_cr_cnt_l24m` int(15) DEFAULT '0' COMMENT '近24月金额小于5000（且大于等于2500）发票作废红冲张数',
  `invoice_lt5000_total_sum_l24m` decimal(20,2) DEFAULT '0.00' COMMENT '近24月金额小于5000（且大于等于2500）发票合计金额税额总和',
  `invoice_lt10000_cnt_l24m` int(15) DEFAULT '0' COMMENT '近24月金额小于10000（且大于等于5000）发票张数',
  `invoice_lt10000_cr_cnt_l24m` int(15) DEFAULT '0' COMMENT '近24月金额小于10000（且大于等于5000）发票作废红冲张数',
  `invoice_lt10000_total_sum_l24m` decimal(20,2) DEFAULT '0.00' COMMENT '近24月金额小于10000（且大于等于5000）发票合计金额税额总和',
  `invoice_gt10000_cnt_l24m` int(15) DEFAULT '0' COMMENT '近24月金额大于10000发票张数',
  `invoice_gt10000_cr_cnt_l24m` int(15) DEFAULT '0' COMMENT '近24月金额大于10000发票作废红冲张数',
  `invoice_gt10000_total_sum_l24m` decimal(20,2) DEFAULT '0.00' COMMENT '近24月金额大于10000发票合计金额税额总和',
  `invoice_detail_cnt_l24m` int(15) DEFAULT '0' COMMENT '近24月附有清单的发票张数',
  `invoice_detail_cr_cnt_l24m` int(15) DEFAULT '0' COMMENT '近24月附有清单的发票作废红冲张数',
  `invoice_detail_total_sum_l24m` decimal(20,2) DEFAULT '0.00' COMMENT '近24月附有清单的发票合计金额税额总和',
  `buyer_cnt_l24m` int(15) DEFAULT '0' COMMENT '近24月交易对手数目',
  `buyer_a_invoice_cnt_l24m` int(15) DEFAULT '0' COMMENT '在统计月归为A类的交易对手近24月开票张数',
  `buyer_b_invoice_cnt_l24m` int(15) DEFAULT '0' COMMENT '在统计月归为B类的交易对手近24月开票张数',
  `buyer_c_invoice_cnt_l24m` int(15) DEFAULT '0' COMMENT '在统计月归为C类的交易对手近24月开票张数',
  `buyer_f_invoice_cnt_l24m` int(15) DEFAULT '0' COMMENT '在统计月归为F类的交易对手近24月开票张数',
  `buyer_a_amt_sum_l24m` decimal(20,2) DEFAULT '0.00' COMMENT '在统计月归为A类的交易对手近24月合计金额总和',
  `buyer_b_amt_sum_l24m` decimal(20,2) DEFAULT '0.00' COMMENT '在统计月归为B类的交易对手近24月合计金额总和',
  `buyer_c_amt_sum_l24m` decimal(20,2) DEFAULT '0.00' COMMENT '在统计月归为C类的交易对手近24月合计金额总和',
  `buyer_f_amt_sum_l24m` decimal(20,2) DEFAULT '0.00' COMMENT '在统计月归为F类的交易对手近24月合计金额总和',
  `invoice_sc_cnt_ratio_6m` decimal(20,2) DEFAULT '0.00' COMMENT '增值税开票张数6个月环比',
  `invoice_sc_cancel_cnt_ratio_6m` decimal(20,2) DEFAULT '0.00' COMMENT '增值税发票作废张数6个月环比',
  `invoice_sc_red_cnt_ratio_6m` decimal(20,2) DEFAULT '0.00' COMMENT '增值税发票红冲张数6个月环比',
  `invoice_sc_total_sum_ratio_6m` decimal(20,2) DEFAULT '0.00' COMMENT '增值税发票合计金额税额总和6个月环比',
  `invoice_cnt_ratio_6m` decimal(20,2) DEFAULT '0.00' COMMENT '所有发票开票张数6个月环比',
  `invoice_total_sum_ratio_6m` decimal(20,2) DEFAULT '0.00' COMMENT '所有发票合计金额税额总和6个月环比',
  `invoice_s_cnt_ratio_6m` decimal(20,2) DEFAULT '0.00' COMMENT '增值税专用发票开票张数6个月环比',
  `invoice_s_total_sum_ratio_6m` decimal(20,2) DEFAULT '0.00' COMMENT '增值税专用发票合计金额税额总和6个月环比',
  `invoice_c_cnt_ratio_6m` decimal(20,2) DEFAULT '0.00' COMMENT '增值税普通发票开票张数6个月环比',
  `invoice_c_total_sum_ratio_6m` decimal(20,2) DEFAULT '0.00' COMMENT '增值税普通发票合计金额税额总和6个月环比',
  `invoice_t_cnt_ratio_6m` decimal(20,2) DEFAULT '0.00' COMMENT '运输发票开票张数6个月环比',
  `invoice_t_total_sum_ratio_6m` decimal(20,2) DEFAULT '0.00' COMMENT '运输发票合计金额税额总和6个月环比',
  `invoice_p_cnt_ratio_6m` decimal(20,2) DEFAULT '0.00' COMMENT '纸质发票开票张数6个月环比',
  `invoice_p_total_sum_ratio_6m` decimal(20,2) DEFAULT '0.00' COMMENT '纸质发票合计金额税额总和6个月环比',
  `invoice_e_cnt_ratio_6m` decimal(20,2) DEFAULT '0.00' COMMENT '电子发票开票张数6个月环比',
  `invoice_e_total_sum_ratio_6m` decimal(20,2) DEFAULT '0.00' COMMENT '电子发票合计金额税额总和6个月环比',
  `invoice_r_cnt_ratio_6m` decimal(20,2) DEFAULT '0.00' COMMENT '卷式发票开票张数6个月环比',
  `invoice_r_total_sum_ratio_6m` decimal(20,2) DEFAULT '0.00' COMMENT '卷式发票合计金额税额总和6个月环比',
  `invoice_red_cnt_rate_ratio_6m` decimal(20,2) DEFAULT '0.00' COMMENT '红冲发票张数占比6个月环比',
  `invoice_cancel_cnt_rate_ratio_6m` decimal(20,2) DEFAULT '0.00' COMMENT '作废发票张数占比6个月环比',
  `invoice_red_total_sum_rate_ratio_6m` decimal(20,2) DEFAULT '0.00' COMMENT '红冲发票合计金额税额总和比率6个月环比',
  `invoice_cancel_total_sum_rate_ratio_6m` decimal(20,2) DEFAULT '0.00' COMMENT '作废发票合计金额税额总和比率6个月环比',
  `invoice_lt100_cnt_ratio_6m` decimal(20,2) DEFAULT '0.00' COMMENT '金额小于100发票张数6个月环比',
  `invoice_lt100_total_sum_ratio_6m` decimal(20,2) DEFAULT '0.00' COMMENT '金额小于100发票合计金额税额总和6个月环比',
  `invoice_lt1000_cnt_ratio_6m` decimal(20,2) DEFAULT '0.00' COMMENT '金额小于1000（且大于等于100）发票张数6个月环比',
  `invoice_lt1000_total_sum_ratio_6m` decimal(20,2) DEFAULT '0.00' COMMENT '金额小于1000（且大于等100）发票合计金额税额总和6个月环比',
  `invoice_lt2500_cnt_ratio_6m` decimal(20,2) DEFAULT '0.00' COMMENT '金额小于2500（且大于等于1000）发票张数6个月环比',
  `invoice_lt2500_total_sum_ratio_6m` decimal(20,2) DEFAULT '0.00' COMMENT '金额小于2500（且大于等于1000）发票合计金额税额总和6个月环比',
  `invoice_lt5000_cnt_ratio_6m` decimal(20,2) DEFAULT '0.00' COMMENT '金额小于5000（且大于等于2500）发票张数6个月环比',
  `invoice_lt5000_total_sum_ratio_6m` decimal(20,2) DEFAULT '0.00' COMMENT '金额小于5000（且大于等于2500）发票合计金额税额总和6个月环比',
  `invoice_gt10000_cnt_ratio_6m` decimal(20,2) DEFAULT '0.00' COMMENT '金额大于10000（且大于等于5000）发票张数6个月环比',
  `invoice_gt10000_total_sum_ratio_6m` decimal(20,2) DEFAULT '0.00' COMMENT '金额大于10000（且大于等于5000）发票合计金额税额总和6个月环比',
  `invoice_detail_cnt_ratio_6m` decimal(20,2) DEFAULT '0.00' COMMENT '附有清单的发票张数6个月环比',
  `invoice_detail_total_sum_ratio_6m` decimal(20,2) DEFAULT '0.00' COMMENT '附有清单的发票合计金额税额总和6个月环比',
  `buyer_cnt_chg_rate_6m` decimal(20,2) DEFAULT '0.00' COMMENT '交易对手数目6个月环比变化率',
  `buyer_a_cnt_chg_rate_6m` decimal(20,2) DEFAULT '0.00' COMMENT 'A类交易对手数目6个月变化率',
  `buyer_b_cnt_chg_rate_6m` decimal(20,2) DEFAULT '0.00' COMMENT 'B类交易对手数目6个月变化率',
  `buyer_c_cnt_chg_rate_6m` decimal(20,2) DEFAULT '0.00' COMMENT 'C类交易对手数目6个月变化率',
  `buyer_f_cnt_chg_rate_6m` decimal(20,2) DEFAULT '0.00' COMMENT 'F类交易对手数目6个月变化率',
  `buyer_a_invoice_cnt_l12m_chg_rate_6m` decimal(20,2) DEFAULT '0.00' COMMENT '近12月A类交易对手开票张数6个月变化率',
  `buyer_b_invoice_cnt_l12m_chg_rate_6m` decimal(20,2) DEFAULT '0.00' COMMENT '近12月B类交易对手开票张数6个月变化率',
  `buyer_c_invoice_cnt_l12m_chg_rate_6m` decimal(20,2) DEFAULT '0.00' COMMENT '近12月C类交易对手开票张数6个月变化率',
  `buyer_f_invoice_cnt_l12m_chg_rate_6m` decimal(20,2) DEFAULT '0.00' COMMENT '近12月F类交易对手开票张数6个月变化率',
  `buyer_a_amt_sum_l12m_chg_rate_6m` decimal(20,2) DEFAULT '0.00' COMMENT '近12月A类交易对手合计金额总和6个月变化率',
  `buyer_b_amt_sum_l12m_chg_rate_6m` decimal(20,2) DEFAULT '0.00' COMMENT '近12月B类交易对手合计金额总和6个月变化率',
  `buyer_c_amt_sum_l12m_chg_rate_6m` decimal(20,2) DEFAULT '0.00' COMMENT '近12月C类交易对手合计金额总和6个月变化率',
  `buyer_f_amt_sum_l12m_chg_rate_6m` decimal(20,2) DEFAULT '0.00' COMMENT '近12月F类交易对手合计金额总和6个月变化率',
  `invoice_sc_cnt_ratio_12m` decimal(20,2) DEFAULT '0.00' COMMENT '增值税开票张数12个月环比',
  `invoice_sc_cancel_cnt_ratio_12m` decimal(20,2) DEFAULT '0.00' COMMENT '增值税发票作废张数12个月环比',
  `invoice_sc_red_cnt_ratio_12m` decimal(20,2) DEFAULT '0.00' COMMENT '增值税发票红冲张数12个月环比',
  `invoice_sc_total_sum_ratio_12m` decimal(20,2) DEFAULT '0.00' COMMENT '增值税发票合计金额税额总和12个月环比',
  `invoice_cnt_ratio_12m` decimal(20,2) DEFAULT '0.00' COMMENT '所有发票开票张数12个月环比',
  `invoice_total_sum_ratio_12m` decimal(20,2) DEFAULT '0.00' COMMENT '所有发票合计金额税额总和12个月环比',
  `invoice_s_cnt_ratio_12m` decimal(20,2) DEFAULT '0.00' COMMENT '增值税专用发票开票张数12个月环比',
  `invoice_s_total_sum_ratio_12m` decimal(20,2) DEFAULT '0.00' COMMENT '增值税专用发票合计金额税额总和12个月环比',
  `invoice_c_cnt_ratio_12m` decimal(20,2) DEFAULT '0.00' COMMENT '增值税普通发票开票张数12个月环比',
  `invoice_c_total_sum_ratio_12m` decimal(20,2) DEFAULT '0.00' COMMENT '增值税普通发票合计金额税额总和12个月环比',
  `invoice_t_cnt_ratio_12m` decimal(20,2) DEFAULT '0.00' COMMENT '运输发票开票张数12个月环比',
  `invoice_t_total_sum_ratio_12m` decimal(20,2) DEFAULT '0.00' COMMENT '运输发票合计金额税额总和12个月环比',
  `invoice_p_cnt_ratio_12m` decimal(20,2) DEFAULT '0.00' COMMENT '纸质发票开票张数12个月环比',
  `invoice_p_total_sum_ratio_12m` decimal(20,2) DEFAULT '0.00' COMMENT '纸质发票合计金额税额总和12个月环比',
  `invoice_e_cnt_ratio_12m` decimal(20,2) DEFAULT '0.00' COMMENT '电子发票开票张数12个月环比',
  `invoice_e_total_sum_ratio_12m` decimal(20,2) DEFAULT '0.00' COMMENT '电子发票合计金额税额总和12个月环比',
  `invoice_r_cnt_ratio_12m` decimal(20,2) DEFAULT '0.00' COMMENT '卷式发票开票张数12个月环比',
  `invoice_r_total_sum_ratio_12m` decimal(20,2) DEFAULT '0.00' COMMENT '卷式发票合计金额税额总和12个月环比',
  `invoice_red_cnt_rate_ratio_12m` decimal(20,2) DEFAULT '0.00' COMMENT '红冲发票张数占比12个月环比',
  `invoice_cancel_cnt_rate_ratio_12m` decimal(20,2) DEFAULT '0.00' COMMENT '作废发票张数占比12个月环比',
  `invoice_red_total_sum_rate_ratio_12m` decimal(20,2) DEFAULT '0.00' COMMENT '红冲发票合计金额税额总和比率12个月环比',
  `invoice_cancel_total_sum_rate_ratio_12m` decimal(20,2) DEFAULT '0.00' COMMENT '作废发票合计金额税额总和比率12个月环比',
  `invoice_lt100_cnt_ratio_12m` decimal(20,2) DEFAULT '0.00' COMMENT '金额小于100发票张数12个月环比',
  `invoice_lt100_total_sum_ratio_12m` decimal(20,2) DEFAULT '0.00' COMMENT '金额小于100发票合计金额税额总和12个月环比',
  `invoice_lt1000_cnt_ratio_12m` decimal(20,2) DEFAULT '0.00' COMMENT '金额小于1000发票张数12个月环比',
  `invoice_lt1000_total_sum_ratio_12m` decimal(20,2) DEFAULT '0.00' COMMENT '金额小于1000发票合计金额税额总和12个月环比',
  `invoice_lt2500_cnt_ratio_12m` decimal(20,2) DEFAULT '0.00' COMMENT '金额小于2500发票张数12个月环比',
  `invoice_lt2500_total_sum_ratio_12m` decimal(20,2) DEFAULT '0.00' COMMENT '金额小于2500发票合计金额税额总和12个月环比',
  `invoice_lt5000_cnt_ratio_12m` decimal(20,2) DEFAULT '0.00' COMMENT '金额小于5000发票张数12个月环比',
  `invoice_lt5000_total_sum_ratio_12m` decimal(20,2) DEFAULT '0.00' COMMENT '金额小于5000发票合计金额税额总和12个月环比',
  `invoice_gt10000_cnt_ratio_12m` decimal(20,2) DEFAULT '0.00' COMMENT '金额大于10000发票张数12个月环比',
  `invoice_gt10000_total_sum_ratio_12m` decimal(20,2) DEFAULT '0.00' COMMENT '金额大于10000发票合计金额税额总和12个月环比',
  `invoice_detail_cnt_ratio_12m` decimal(20,2) DEFAULT '0.00' COMMENT '附有清单的发票张数12个月环比',
  `invoice_detail_total_sum_ratio_12m` decimal(20,2) DEFAULT '0.00' COMMENT '附有清单的发票合计金额税额总和12个月环比',
  `buyer_cnt_chg_rate_12m` decimal(20,2) DEFAULT '0.00' COMMENT '交易对手数目12个月环比变化率',
  `buyer_a_cnt_chg_rate_12m` decimal(20,2) DEFAULT '0.00' COMMENT 'A类交易对手数目12个月环比变化率',
  `buyer_b_cnt_chg_rate_12m` decimal(20,2) DEFAULT '0.00' COMMENT 'B类交易对手数目12个月环比变化率',
  `buyer_c_cnt_chg_rate_12m` decimal(20,2) DEFAULT '0.00' COMMENT 'C类交易对手数目12个月环比变化率',
  `buyer_f_cnt_chg_rate_12m` decimal(20,2) DEFAULT '0.00' COMMENT 'F类交易对手数目12个月变化率',
  `buyer_a_invoice_cnt_l12m_chg_rate_12m` decimal(20,2) DEFAULT '0.00' COMMENT '近12月A类交易对手开票张数12个月变化率',
  `buyer_b_invoice_cnt_l12m_chg_rate_12m` decimal(20,2) DEFAULT '0.00' COMMENT '近12月B类交易对手开票张数12个月变化率',
  `buyer_c_invoice_cnt_l12m_chg_rate_12m` decimal(20,2) DEFAULT '0.00' COMMENT '近12月C类交易对手开票张数12个月变化率',
  `buyer_f_invoice_cnt_l12m_chg_rate_12m` decimal(20,2) DEFAULT '0.00' COMMENT '近12月F类交易对手开票张数12个月变化率',
  `buyer_a_amt_sum_l12m_chg_rate_12m` decimal(20,2) DEFAULT '0.00' COMMENT '近12月A类交易对手合计金额总和12个月变化率',
  `buyer_b_amt_sum_l12m_chg_rate_12m` decimal(20,2) DEFAULT '0.00' COMMENT '近12月B类交易对手合计金额总和12个月变化率',
  `buyer_c_amt_sum_l12m_chg_rate_12m` decimal(20,2) DEFAULT '0.00' COMMENT '近12月C类交易对手合计金额总和12个月变化率',
  `buyer_f_amt_sum_l12m_chg_rate_12m` decimal(20,2) DEFAULT '0.00' COMMENT '近12月F类交易对手合计金额总和12个月变化率',
  `is_delete` tinyint(4) DEFAULT NULL COMMENT '逻辑删除，1.是，0.否',
  `create_time` date DEFAULT NULL COMMENT '创建时间',
  `create_user` varchar(100) DEFAULT NULL COMMENT '创建人',
  `modify_time` date DEFAULT NULL COMMENT '修改时间',
  `modify_user` varchar(100) DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (`id`),
  UNIQUE KEY `index_unique` (`mcht_cd`,`data_month`),
  KEY `idx_mcht_cd_data_month` (`mcht_cd`,`data_month`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='【税金贷】跨月统计表';



--交易对手表
DROP TABLE IF EXISTS data_warehouse.counterparty;
CREATE TABLE `counterparty` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `mcht_cd` varchar(50) DEFAULT NULL COMMENT '商户申请编号',
  `data_month` varchar(50) DEFAULT NULL COMMENT '统计月份',
  `buyer_name` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `buyer_tax_cd` varchar(50) DEFAULT NULL COMMENT '交易对手税号',
  `buyer_invoice_cnt` int(15) DEFAULT '0' COMMENT '交易对手发票张数',
  `buyer_invoice_cr_cnt` int(15) DEFAULT '0' COMMENT '交易对手发票作废红冲张数',
  `buyer_invoice_amt_sum` decimal(20,2) DEFAULT '0.00' COMMENT '交易对手发票合计金额',
  `buyer_invoice_tax_sum` decimal(20,2) DEFAULT '0.00' COMMENT '交易对手发票合计税额',
  `buyer_invoice_total_sum` decimal(20,2) DEFAULT '0.00' COMMENT '交易对手发票合计金额税额总和',
  `is_delete` tinyint(4) DEFAULT NULL COMMENT '逻辑删除，1.是，0.否',
  `create_time` date DEFAULT NULL COMMENT '创建时间',
  `create_user` varchar(100) DEFAULT NULL COMMENT '创建人',
  `modify_time` date DEFAULT NULL COMMENT '修改时间',
  `modify_user` varchar(100) DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (`id`),
  UNIQUE KEY `index_unique` (`mcht_cd`,`data_month`,`buyer_name`,`buyer_tax_cd`),
  KEY `idx_mcht_cd` (`mcht_cd`),
  KEY `idx_data_month` (`data_month`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='【税金贷】交易对手表';

--交易对手分类表
DROP TABLE IF EXISTS data_warehouse.counterparty_classify;

CREATE TABLE `counterparty_classify` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增主键',
  `mcht_cd` varchar(50) DEFAULT NULL COMMENT '商户申请编号',
  `data_month` varchar(50) DEFAULT NULL COMMENT '统计月份',
  `buyer_name` varchar(100) CHARACTER SET utf8 COLLATE utf8_bin DEFAULT NULL,
  `buyer_tax_cd` varchar(50) DEFAULT NULL COMMENT '交易对手税号',
  `buyer_hist_month` int(15) DEFAULT '0' COMMENT '交易对手交易历史总月份数',
  `buyer_invoice_cnt_l24m` int(15) DEFAULT '0' COMMENT '交易对手近24月开票张数',
  `buyer_invoice_total_sum_l24m` decimal(20,2) DEFAULT '0.00' COMMENT '交易对手近24月合计金额税额总和',
  `buyer_invoice_cnt_l12m` int(15) DEFAULT '0' COMMENT '交易对手近12月开票张数',
  `buyer_invoice_total_sum_l12m` decimal(20,2) DEFAULT '0.00' COMMENT '交易对手近12月合计金额税额总和',
  `buyer_invoice_cnt_l6m` int(15) DEFAULT '0' COMMENT '交易对手近6月开票张数',
  `buyer_invoice_total_sum_l6m` decimal(20,2) DEFAULT '0.00' COMMENT '交易对手近6月合计金额税额总和',
  `buyer_invoice_cnt_l3m` int(15) DEFAULT '0' COMMENT '交易对手近3月开票张数',
  `buyer_invoice_total_sum_l3m` decimal(20,2) DEFAULT '0.00' COMMENT '交易对手近3月合计金额税额总和',
  `buyer_invoice_cnt_l712m` int(15) DEFAULT NULL COMMENT '交易对手近7-12月开票张数',
  `buyer_invoice_total_sum_l712m` decimal(20,2) DEFAULT NULL COMMENT '交易对手近7-12月合计金额税额总和',
  `buyer_invoice_cnt_l1324m` int(15) DEFAULT NULL COMMENT '交易对手近13-24月开票张数',
  `buyer_invoice_total_sum_l1324m` decimal(20,2) DEFAULT NULL COMMENT '交易对手近13-24月合计金额税额总和',
  `buyer_invoice_cnt_l1m` int(15) DEFAULT '0' COMMENT '交易对手近1月（统计当月）开票张数',
  `buyer_invoice_total_sum_l1m` decimal(20,2) DEFAULT '0.00' COMMENT '交易对手近1月（统计当月）合计金额税额总和',
  `buyer_type` varchar(50) DEFAULT NULL COMMENT '交易对手类型',
  `is_delete` tinyint(4) DEFAULT NULL COMMENT '逻辑删除，1.是，0.否',
  `create_time` date DEFAULT NULL COMMENT '创建时间',
  `create_user` varchar(100) DEFAULT NULL COMMENT '创建人',
  `modify_time` date DEFAULT NULL COMMENT '修改时间',
  `modify_user` varchar(100) DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (`id`),
  UNIQUE KEY `index_unique` (`mcht_cd`,`data_month`,`buyer_name`,`buyer_tax_cd`),
  KEY `idx_mcht_cd_data_month` (`mcht_cd`,`data_month`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='【税金贷】交易对手分类表';


