

--月统计表
-- DROP TABLE IF EXISTS dm_taxloan.statistics_month;
CREATE TABLE IF NOT EXISTS ${hivevar:DATABASE_DEST}.statistics_month(
                                            mcht_cd String COMMENT '销方商户编号',
                                            data_month String COMMENT '统计月份',
                                            invoice_sc_cnt int COMMENT '增值税开票张数',
                                            invoice_sc_cancel_cnt int COMMENT '增值税发票作废张数',
                                            invoice_sc_red_cnt int COMMENT '增值税发票红冲张数',
                                            invoice_sc_total_sum decimal(20,2) COMMENT '增值税发票合计金额税额总和',

                                            invoice_cnt int COMMENT '所有发票开票张数',
                                            invoice_cr_cnt int COMMENT '所有发票作废红冲张数',
                                            invoice_amt_sum decimal(20,2) COMMENT '所有发票合计金额',
                                            invoice_tax_sum decimal(20,2) COMMENT '所有发票合计税额',
                                            invoice_total_sum decimal(20,2) COMMENT '所有发票合计金额税额总和',
    --所有发票统计新增4个字段
                                            invoice_cancel_cnt int COMMENT '所有发票作废张数',
                                            invoice_red_cnt int COMMENT '所有发票红冲张数',
                                            invoice_total_c_sum decimal(20,2) COMMENT '所有作废发票合计金额税额总和',
                                            invoice_total_r_sum decimal(20,2) COMMENT '所有红冲发票合计金额税额总和',


                                            invoice_s_cnt int COMMENT '增值税专用发票开票张数',
                                            invoice_s_cancel_cnt int COMMENT '增值税专用发票作废张数',
                                            invoice_s_red_cnt int COMMENT '增值税专用发票红冲张数',
                                            invoice_s_amt_sum decimal(20,2) COMMENT '增值税专用发票合计金额',
                                            invoice_s_tax_sum decimal(20,2) COMMENT '增值税专用发票合计税额',
                                            invoice_s_total_sum decimal(20,2) COMMENT '增值税专用发票合计金额税额总和',
                                            invoice_c_cnt int COMMENT '增值税普通发票开票张数',
                                            invoice_c_cancel_cnt int COMMENT '增值税普通发票作废张数',
                                            invoice_c_red_cnt int COMMENT '增值税普通发票红冲张数',
                                            invoice_c_amt_sum decimal(20,2) COMMENT '增值税普通发票合计金额',
                                            invoice_c_tax_sum decimal(20,2) COMMENT '增值税普通发票合计税额',
                                            invoice_c_total_sum decimal(20,2) COMMENT '增值税普通发票合计金额税额总和',
                                            invoice_t_cnt int COMMENT '运输发票开票张数',
                                            invoice_t_cancel_cnt int COMMENT '运输发票作废张数',
                                            invoice_t_red_cnt int COMMENT '运输发票红冲张数',
                                            invoice_t_amt_sum decimal(20,2) COMMENT '运输发票合计金额',
                                            invoice_t_tax_sum decimal(20,2) COMMENT '运输发票合计税额',
                                            invoice_t_total_sum decimal(20,2) COMMENT '运输发票合计金额税额总和',
                                            invoice_p_cnt int COMMENT '纸质发票开票张数',
                                            invoice_p_cancel_cnt int COMMENT '纸质发票作废张数',
                                            invoice_p_red_cnt int COMMENT '纸质发票红冲张数',
                                            invoice_p_amt_sum decimal(20,2) COMMENT '纸质发票合计金额',
                                            invoice_p_tax_sum decimal(20,2) COMMENT '纸质发票合计税额',
                                            invoice_p_total_sum decimal(20,2) COMMENT '纸质发票合计金额税额总和',
                                            invoice_e_cnt int COMMENT '电子发票开票张数',
                                            invoice_e_cancel_cnt int COMMENT '电子发票作废张数',
                                            invoice_e_red_cnt int COMMENT '电子发票红冲张数',
                                            invoice_e_amt_sum decimal(20,2) COMMENT '电子发票合计金额',
                                            invoice_e_tax_sum decimal(20,2) COMMENT '电子发票合计税额',
                                            invoice_e_total_sum decimal(20,2) COMMENT '电子发票合计金额税额总和',
                                            invoice_r_cnt int COMMENT '卷式发票开票张数',
                                            invoice_r_cancel_cnt int COMMENT '卷式发票作废张数',
                                            invoice_r_red_cnt int COMMENT '卷式发票红冲张数',
                                            invoice_r_amt_sum decimal(20,2) COMMENT '卷式发票合计金额',
                                            invoice_r_tax_sum decimal(20,2) COMMENT '卷式发票合计税额',
                                            invoice_r_total_sum decimal(20,2) COMMENT '卷式发票合计金额税额总和',
                                            invoice_red_cnt_rate decimal(20,2) COMMENT '红冲发票张数占比',
                                            invoice_cancel_cnt_rate decimal(20,2) COMMENT '作废发票张数占比',
                                            invoice_red_total_sum_rate decimal(20,2) COMMENT '红冲发票合计金额税额总和比率',
                                            invoice_cancel_total_sum_rate decimal(20,2) COMMENT '作废发票合计金额税金总和比率',
                                            invoice_lt100_cnt int COMMENT '金额小于100发票张数',
                                            invoice_lt100_cr_cnt int COMMENT '金额小于100发票作废红冲张数',
                                            invoice_lt100_total_sum decimal(20,2) COMMENT '金额小于100发票合计金额税额总和',
                                            invoice_lt1000_cnt int COMMENT '金额小于1000（且大于等于100）发票张数',
                                            invoice_lt1000_cr_cnt int COMMENT '金额小于1000（且大于等于100）发票作废红冲张数',
                                            invoice_lt1000_total_sum decimal(20,2) COMMENT '金额小于1000（且大约等于100）发票合计金额税额总和',
                                            invoice_lt2500_cnt int COMMENT '金额小于2500（且大于等于1000）发票张数',
                                            invoice_lt2500_cr_cnt int COMMENT '金额小于2500（且大于等于1000）发票作废红冲张数',
                                            invoice_lt2500_total_sum decimal(20,2) COMMENT '金额小于2500（且大于等于1000）发票合计金额税额总和',
                                            invoice_lt5000_cnt int COMMENT '金额小于5000（且大于等于2500）发票张数',
                                            invoice_lt5000_cr_cnt int COMMENT '金额小于5000（且大于等于2500）发票作废红冲张数',
                                            invoice_lt5000_total_sum decimal(20,2) COMMENT '金额小于5000（且大于等于2500）发票合计金额税额总和',
                                            invoice_lt10000_cnt int COMMENT '金额小于10000（且大于等于5000）发票张数',
                                            invoice_lt10000_cr_cnt int COMMENT '金额小于10000（且大于等于5000）发票作废红冲张数',
                                            invoice_lt10000_total_sum decimal(20,2) COMMENT '金额小于10000（且大于等于5000）发票合计金额税额总和',
                                            invoice_gt10000_cnt int COMMENT '金额大于10000发票张数',
                                            invoice_gt10000_cr_cnt int COMMENT '金额大于10000发票作废红冲张数',
                                            invoice_gt10000_total_sum decimal(20,2) COMMENT '金额大于10000发票合计金额税额总和',
                                            invoice_detail_cnt int COMMENT '附有清单的发票张数',
                                            invoice_detail_cr_cnt int COMMENT '附有清单的发票作废红冲张数',
                                            invoice_detail_total_sum decimal(20,2) COMMENT '附有清单的发票合计金额税额总和',
                                            buyer_cnt int COMMENT '统计月交易对手数目',
                                            buyer_cnt_all int COMMENT '截至统计月所有交易对手数目',
                                            buyer_a_cnt int COMMENT '在统计月归为A类的交易对手数目',
                                            buyer_b_cnt int COMMENT '在统计月归为B类的交易对手数目',
                                            buyer_c_cnt int COMMENT '在统计月归为C类的交易对手数目',
                                            buyer_f_cnt int COMMENT '在统计月归为F类的交易对手数目',
                                            is_delete String COMMENT '逻辑删除，1.是，0.否',
    --create_time date COMMENT '创建时间',
                                            create_user String COMMENT '创建人',
                                            modify_time timestamp COMMENT '修改时间',
                                            modify_user String COMMENT '修改人'
)COMMENT '【税金贷】商户月统计表 ' partitioned by (create_time string)
    ROW FORMAT DELIMITED FIELDS TERMINATED BY '\0001' stored AS orc
