CREATE TABLE ${hivevar:DATABASE_DEST}.saleinvoicedetail
( `cid` string,
  `amount` double,
  `billid` string,
  `calcunit` string,
  `detaillistflag` boolean,
  `indexno` double,
  `invoicedetailno` double,
  `invoiceid` string,
  `invoicelineprop` int,
  `notaxprice` double,
  `quantity` double,
  `standardtype` string,
  `taxamount` double,
  `taxprice` double,
  `taxpriceflag` boolean,
  `taxrate` double,
  `useflag` boolean,
  `waresname` string,
  `waresno` string,
  `warestaxitem` string)